import './globals.css'
// import { Inter } from 'next/font/google'
// const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html>
      <body>
        <div className="px-8 lg:w-[1024px] xl:w-[1280px] 2xl:w-[1536px]">
          {children}
        </div>
      </body>
    </html>
  )
}
